#!/usr/bin/python
############################
# Python script
# Author : Mickael Menard
# Date : 2017/11/05
# version: 0.1
#
# Clean .dop files generated by DxO Optics Pro / PhotoLab
#
# Usage:
#	./dopclean <files_list>
#	./dopclean *.dop
#	./dopclean *.*
#
############################

import sys
if sys.version_info < (2,7):
  sys.stderr.write("This script requires Python 2.7 or newer.\n")
  sys.stderr.write("Current version: " + sys.version + "\n")
  sys.stderr.flush()
  sys.exit(1)
import os, shutil

# Local global constants
VERSION = '0.1'							# Script version
AUTOMATOR=0								# Automator flag, 0:disabled, Enabled otherwise
DEBUG=1									# debug mode, 0:disabled, Enabled otherwise
LOG_FILE_ENABLED=1						# 0: Disabled, Enabled otherwise
LOG_FILE_NAME="log.txt"					# Redirect debug print in a log
RAW_EXT=".ARW"							# RAW file extention (can be modified)
DOP_EXT=".dop"							# Extention of .dop file generated by DxO
SEPARATOR_STR="#################"

if(AUTOMATOR==1):
	DEBUG=0				# Keep output print disabled if the script is used in automator once there is no redirection in a log file
	LOG_FILE_ENABLED=0	# To be enabled for debugging purposes

def log(file, str):
	try:
		file.write(str+"\n")
	except:
		pass
	if DEBUG:
		print "%s\n" % str,

def main():
	# Log File
	if(LOG_FILE_ENABLED):
		logfile = open(os.getcwd()+"/"+LOG_FILE_NAME, "w")
		#logfile = open("/Users/subwarez/"+LOG_FILE_NAME, "w")	# For Automator debugging
		if DEBUG:
			print "DEBUG: log %s created" % os.getcwd()+"/"+LOG_FILE_NAME
			
	log(logfile, ".dop files cleanup v%s" % VERSION)
	# Debug, current location
	if DEBUG:
		log(logfile,"Script executed from: %s" % os.getcwd())

	# Check inputs
	if len(sys.argv) == 1:
		log(logfile, "No input file(s)")
		try:
			logfile.close()
		except:
			pass
		sys.exit()
	else:
		log(logfile, "%d file(s) to be processed..." % (len(sys.argv)-1))


	# List input files
	if DEBUG!=0:
		# List all input files
		log(logfile, "Input files list:")
		for file_in in sys.argv[1:]:
			if(os.path.isdir(file_in) == 1):
				log(logfile, "DEBUG: %s is dir" % file_in)
				log(logfile, os.listdir(file_in))				# TEMP, need strings
			else:
				log(logfile, "DEBUG: file_in = %s" % file_in)
		log(logfile, SEPARATOR_STR)

	# For each file
	for file_in in sys.argv[1:]:
		if(os.path.isdir(file_in) == 1):
			log(logfile, "DEBUG: %s is dir : NOT SUPPORTED" % file_in)
			# TODO
			continue
		folder, fullname = os.path.split(file_in)
		name, ext = os.path.splitext(fullname)
		
		if(ext != DOP_EXT):
			log(logfile, "Not a dop file => ignore")
			log(logfile, SEPARATOR_STR)
			continue
		else:
			log(logfile, "DEBUG: file_in = %s" % file_in)
			log(logfile, "DEBUG: folder = %s" % folder)
			log(logfile, "DEBUG: base = %s" % fullname)
			log(logfile, "DEBUG: name = %s" % name)
			log(logfile, "DEBUG: ext = %s" % ext)

			# Get the RAW name
			subname, subext = os.path.splitext(name)
			log(logfile, "DEBUG: subname = %s" % subname)
			log(logfile, "DEBUG: subext = %s" % subext)
			log(logfile, "DEBUG: %s" % (subname+RAW_EXT))
			
			if (os.path.isfile(folder+"/"+subname+RAW_EXT) == 0):
				os.remove(folder+"/"+fullname)
				log(logfile, (folder+"/"+fullname+" removed"))
			else:
				log(logfile, "RAW file exist => ignore")
		log(logfile, SEPARATOR_STR)
	
	# Close log file
	if(LOG_FILE_NAME):
		logfile.close()
 
if __name__ == "__main__":
	main()